### ISSUE TITLE
Method to reconcile world coordinates after each calibration or setup

### ISSUE THREAD

**Issue by damonseeley** [OpenPTrack/open_ptrack#10]
A similar tracking system has a feature that we suggest could be useful: Once cameras are registered to each other two or more physical camera locations could be entered into a config file, relative to a logical origin.  Then one could "Adjust World Coordinates" to reconcile new calibrations against a known space and tracking data would be consistent even after re-calibrations.

**Comment by mmunaro** [comment]
This enhancement has been provided with commit b023a89b218d96b2378c896c1ed51b990b6f4ae1.
Now two points on the images can be selected and coordinates provided in order to define a new reference frame.
While creating files for calibration with 
roslaunch opt_calibration calibration_initializer.launch
a new file that launches the GUI for defining the new reference frame is created and can be launched with
roslaunch opt_calibration opt_define_reference_frame.launch

Then, instructions are provided via command line.

Instructions on this procedure should be added to the Wiki.

Closing this issue.
