### ISSUE TITLE
Will OpenPTrack run on this Intel Robotic Development Kit with RealSense camera

### ISSUE THREAD

**Issue by apavani** [OpenPTrack/open_ptrack#102]
Hi there,
I was wondering if this combined modular system by Intel - called Intel Robotic Development Kit that runs Ubuntu and promises to run with RealSense be able to run OpenPtrack.
Will you guys be okay to test it on this hardware or at least give us some idea whether OpenPTrack would work at all?
http://click.intel.com/intelr-realsensetm-robotic-development-kit.html

OpenPTrack is an excellent system. We got it running on 2 desktop computers. However, if the hardware can be modular it could be very well used to track people in a large space with lots of cameras. Sadly, the results with the Jetson TK1 didn't seem to be that promising

**Comment by mmunaro** [comment]
Hi,
OpenPTrack is tested with Ubuntu 14.04 and I suppose you can install it on that board.
Thus, I think you could use OpenPTrack with that board, but you would need to add the ROS wrapper for the Intel RealSense sensor, since it is not present in OpenPTrack yet.
You could not use Kinect v2 on that board since it does not have an Nvidia GPU.

For Jetson TK1 and TX1, OpenPTrack has a branch here:
https://github.com/OpenPTrack/open_ptrack/tree/jetson-dev

For streaming Kinect v2 point clouds, we got 22 fps on TK1 and 30 fps on TX1.
For people detection, we got 14 fps on TK1 and 23 fps on TX1.

**Comment by endquote** [comment]
Cool. We may give it a shot. The size and price is pretty appealing, vs the TX1 and Kinect 2. Do you think  the performance will be any good? Of course you can only guess.

**Comment by mmunaro** [comment]
Since Realsense uses structured light, I think the performance will be close to that of Kinect v1, but inferior to what you could obtain with Kinect v2.

**Comment by mikjh** [comment]
Hi @endquote, did you get the Realsense camera working with OpenPTrack? I am considering using the Realsense cameras as well. Did you get any performance data?

**Comment by endquote** [comment]
This would also be fun to try:
http://click.intel.com/intel-aero-platform-for-uavs-compute-board.html
http://click.intel.com/intel-aero-platform-for-uavs-vision-accessory-kit.html

/cc @igierard

**Comment by endquote** [comment]
And also:
https://newsroom.intel.com/chip-shots/make-amazing-things-happen-iot-entrepreneurship-intel-joule/

**Comment by jburkeucla** [comment]
Yes, we’ve been watching this development; just looking for development cycles to try to get a port going...
- Jeff
