### ISSUE TITLE
Providing depth images from another application

### ISSUE THREAD

**Issue by Karnix** [OpenPTrack/open_ptrack#111]
HI! First of all thank you for this amazing library and its equally good documentation.

I just wanted to know if it's possible to provide OpenPTrack with already processed depth images. I have a custom made stereo rig from which I'm creating depth images on a Jetson TX1. Can I somehow pass these depth images to this library?

**Comment by marketto89** [comment]
@Karnix,

the short answer to your question is no, if your camera is not [supported](https://github.com/OpenPtrack/open_ptrack/wiki/Supported-Hardware) it is not possible to use OpenPtrack in an easy way.

Nevertheless, if you are/become familiar with ROS it is possible to adapt some code and make it work.

Just a couple of questions to better understand your situation:
1. Do you want to use OpenPTrack with only one camera or in a camera network?
2. Are the depth images computed offline or are we speaking about a stream of depth images?

**Comment by Karnix** [comment]
The answer to your questions,
1 - With a single stereo camera (made from two standard logitech cameras)
2 - I'm computing the depth images in real time and publishing them as ros topics too

**Comment by marketto89** [comment]
Actually, you want to use OpenPTrack using only one camera. Most of the wiki you will find is about the camera network calibration. Since this passage is not required for you, I suggest to launch the people detection and tracking directly with `roslaunch tracking detection_and_tracking_stereo.launch` after some changes.

Here are the passages i would do if I were you:

1. Transform and stream the depth images to a point cloud topic (take a look [here](http://wiki.ros.org/depth_image_proc))
2. Look if the generated point clouds make sense. If you are not able to detect people looking at the cloud the algorithm will not perform better than you.
3. You may want to change this [file](https://github.com/OpenPTrack/open_ptrack/blob/development/detection/launch/detector_stereo.launch). You may comment the camera driver and stereo processing part since you are already able to stream the point clouds. Finally, you should adapt the last parts of the file reflecting the information you have (point cloud topic, camera info topic, ...).
4. Launch `roslaunch tracking detection_and_tracking_stereo.launch`

Of course, all these passages are not tested, so you should expect to do some debug.

**Comment by Karnix** [comment]
Alright, thanks!

But I'm doing all this on a Jetson TX1 and on your Jetson documentation wiki page you've mentioned it can't be used to run the master process.

This doesn't apply to a single sensor setup right?

**Comment by marketto89** [comment]
In an OpenPTrack camera network, the master computer takes care of fusing the different detections coming from all the nodes and perform the tracking.

This process is time consuming and is preferable to have an high/end computer to do this.

With a single sensor the effort required is not so huge, so the TX1 should perform correctly the detection and tracking.

**Comment by Karnix** [comment]
Great!
Will try it out then :)

**Comment by Karnix** [comment]
One more question,
In this scenario is OpenPTrack still going to give me GPU accelerated results?

**Comment by Karnix** [comment]
One more question,
In this scenario is OpenPTrack still going to give me GPU accelerated results?
