### ISSUE TITLE
Intrinsic Calibration Error: service already advertised - No checkerboard found

### ISSUE THREAD

**Issue by adielfernandez** [OpenPTrack/open_ptrack#130]
I finished the pre-calibration configuration and have moved on to the intrinsic calibration of my Kinect v2 cameras but I keep getting an error when running the script to do the first checkerboard test:

`rosrun kinect2_calibration kinect2_calibration record color chess6x5x0.098 -color /kinect2_head/mono/image -ir /kinect2_head/ir/image -interval 1 ~/tmp/
`

After holding the checker board in pretty much ideal conditions for a long while, no grid is found by the system and I get the error shown below:

```
Start settings:
Mode: record
Source: color
Board: chess
Dimensions: 6 x 5
Field size: 0.098
Topic color: /kinect2_head/mono/image
Topic ir: /kinect2_head/ir/image
Auto saving interval: 1
Path: /home/sensor2/tmp/

starting recorder...
[ERROR] [1492467972.692537358]: Tried to advertise a service that is already advertised in this node [/kinect2_calib/compressed/set_parameters]

```

Naturally, I am running "roslaunch kinect2_bridge kinect2_bridge.launch" in another terminal window and the kinect2_calibration above in a separate window.

Side note: I had to change the MASTER URI field in bashrc file back to localhost from the address of my actual master PC or the kinect2_bridge script would not run. Could this be related?

**Comment by marketto89** [comment]
@adielfernandez, 

First of all, if you are using a Kinect v2, the intrinsic calibration is not so important for people tracking purposes. Indeed, the default intrinsic parameters provided by kinect2_bridge are enough and provide good results (for that task).

Anyway, if you want to calibrate your sensor, the error you are reporting should not affect the node capabilities.

From my experience the checkerboard is usually not detected in one of the following cases:

- There are no white borders around the checkerboard.
- The measurements specified in the config file do not fit the checkerboard you are using (i.e. your checkerboard is not 6x5x0.098). In this case, the problem is more likely the number of rows and cols not the square size. 

Could you please check and/or post a picture of the checkerboard you are using?

By the way, the problem should not be related to the change of `MASTER_URI`. This variable simply indicates to the ROS nodes where they should look for a `roscore` process before starting.

**Comment by adielfernandez** [comment]
![screenshot from 2017-04-17 19 35 44](https://cloud.githubusercontent.com/assets/2591545/25108632/39a9b9a2-23a5-11e7-953a-119cf82ef2bd.png)

Thanks for the quick reply. The checkerboard I'm using is the same one included in the openptrack docs. As you can see from the image, the conditions are near ideal. When I see the point cloud in RViz, the color data is fairly obviously out of alignment with the depth data. But maybe that's ok for pure body tracking? I need to get as much precision as I can from the system for this project, unfortunately.

**Comment by marketto89** [comment]
@adielfernandez,

the checkerboard in the picture is not 6x5, but 5x4. Surely, the detection problem you have is (also) because of this.

**Comment by adielfernandez** [comment]
Talk about confusing. So the dimensions are not the number of rows and columns but the "interior vertex points". My apologies.

**Comment by nanodust** [comment]
for clarification see https://github.com/OpenPTrack/open_ptrack/blob/master/docs/images/CheckerBoard_Origion.JPG

**Comment by nanodust** [comment]
and I'll second the fact that intrinsic is not worth the effort w/ Kinect 2. Skipping the step entirely does not noticeably impact accuracy as it does with Kinect 1.

**Comment by adielfernandez** [comment]
Ok, good to know! Thanks again.
