### ISSUE TITLE
why is the rviz ground plane not aligned w/ kinect 2 ground plane

### ISSUE THREAD

**Issue by nanodust** [OpenPTrack/open_ptrack#48]
I have ground plane detection to manual - after picking 3 colinear points, detection (sort of) works, but I can't confirm if the ground plane is correct (and thus affecting detection quality) due to the view. 
![screenshot from 2015-07-21 18 49 29](https://cloud.githubusercontent.com/assets/65142/8815046/80cf7fcc-2fd9-11e5-8850-5ac1a5a32a0a.png)

this is a single camera system, running via roslaunch tracking detection_and_tracking_kinect2.launch, no camera_network  yaml, intrinsic or extrinsic yet performed.

**Comment by mmunaro** [comment]
This is normal if you did not perform extrinsic calibration.
Even if you have a single camera system, you need to perform the extrinsic calibration (in this case it just consists in the ground estimation part with the checkerboard on the floor) in order to perform tracking in the reference frame of the ground.
Detection performance is anyway not affected by the missing calibration, but tracking is.

**Comment by nanodust** [comment]
great to know - I will make a checkerboard ! thanks !!
