### ISSUE TITLE
people tracking skeleton

### ISSUE THREAD

**Issue by cherltte** [OpenPTrack/open_ptrack#72]
Hi,

First off, I appreciate for good solid people tracking system! I am enjoying working with it now! :) Although it wasn't easy for novice, beginner to install despite of its well written description. 

Since it's running very smoothly, I want to do something more with it. more challenging. 2 questions:
1. Can it detect for z-axis? people jumping for instance?
2. Is it possible to integrate with gesture detection like what normal Kinect do?
(I saw from one of your movie showing tracked data of skeleton people walking around. )

This seems more like requests and question rather than an issue, but I didn't know where to put it.

Thank YOu! :)

rcp

**Comment by nanodust** [comment]
1. Can it detect for z-axis? people jumping for instance?

yes - provided you have set the ground plane, it will report centroid shifts. IE - jumping. 

2. Is it possible to integrate with gesture detection like what normal Kinect do?

not out of the box. By design, OPT reports centroid, not skeleton or hands. Even if one did the (significant) development effort to integrate the skeletal detection, the range of the 'gesture' detection would be smaller than the overall integrated tracking area for OPT.  

If you really want a skeleton or gesture, fastest path is to set up a 2nd kinect, and use a different codebase to do feature detection. The UDP of centroid, and coordinate space of the kinect, could indeed be manually calibrated for gesture.

**Comment by cherltte** [comment]
@nanodust,
Thanks for the reply! I have provided ground plane(something that has been done during calibration). I was wondering if there is any setting to enable z-axis data.
according to data description,
"{"header":{"seq":71251,"stamp":{"sec":1415305737,"nsec":110138944},"frame_id":"world"},"tracks": [{"id":387,"x":-0.89131,"y":2.41851,"height":1.55837,"age":29.471,"confidence".0500193}]}"
it only provides x,y coordinate. use height? perhaps?

**Comment by nanodust** [comment]
Yes, height
