### ISSUE TITLE
can orbbec astra sensor run in open ptrack

### ISSUE THREAD

**Issue by motionagus** [OpenPTrack/open_ptrack#76]
i have orbbec astra sensor, knowing its has same functionality as kinect2 and suport openni2 driver is it posible using this sensor in openptrack ? if it posible how to do it ?

**Comment by mmunaro** [comment]
Orbec sensor is not yet supported out of the box, even though it provides the right data to be used with OpenPTrack. It is more similar to Kinect v1 than to Kinect v2 though.

You could probably just use it as a Kinect v1, but you at least need to change the driver that is used for that camera because OpenPTrack uses the OpenNI1 driver for Kinect v1, while you said that Orbec Astra is working with OpenNI2.

**Comment by motionagus** [comment]
oh, so its like that. btw why you said orbbec astra more similar to kinect v1 dude, can you explain more ?

**Comment by mmunaro** [comment]
Because it uses structured-light to estimate depth, as Kinect v1.

**Comment by motionagus** [comment]
oh, i see :) i dont know that, so that cheap for reason. thanks dude, this community support is reliable

**Comment by ccempathy** [comment]
Have you achieved to apply the orbbec astra sensor into openptrack successfully? Look forward to your reply.thanks!

**Comment by jburkeucla** [comment]
Unfortunately there is no support at this time.  We can provide basic guidelines to others to try to integrate it however - basically a wrapper for ROS needs to be created.

**Comment by ccempathy** [comment]
I don't know a lot about the wrapper for ROS Can you explain it detailedly?

**Comment by joaocandre** [comment]
I would also be interested in this.

@jburkeucla where could I find those basic guidelines?
