### ISSUE TITLE
Setting a threshold to refine tracking, and eliminate false positives

### ISSUE THREAD

**Issue by apavani** [OpenPTrack/open_ptrack#95]
We are using the openPTrack system with 4 Kinect 1 cameras. We have successfully calibrated the system and have performed calibration refinement. We've tried re calibrating the system several times. While we are able to see tracking output in an rviz window, the output shows a lot of jitter. It detects a lot of background objects as people, thereby showing us false positives. We've also run 
`rosrun rqt_reconfigure rqt_reconfigure`

and played with different refinement settings like background subtraction, denoising, min and max height of a person etc.
But, in spite of trying all these settings, the system still picks up a lot of background objects as people. 

Can someone give us more pointers on how to reduce the noise or make our tracking more robust, so that it always detects people smoothly and ignores all the background objects.

**Comment by jburkeucla** [comment]
It’s great to hear that you have this running. Can you please post some images of the environment and the false positives you are seeing?

**Comment by igierard** [comment]
Hello I work with @apavani since posting this we have switched to using 2 kinect twos. Here are some photos of the space we are in. 

![file_003](https://cloud.githubusercontent.com/assets/189820/15551551/5e30766c-226b-11e6-90cf-3fa606222c20.jpeg)


![file_002](https://cloud.githubusercontent.com/assets/189820/15551552/5e328bd2-226b-11e6-81ec-fd98506a2031.jpeg)

![file_001_scaled](https://cloud.githubusercontent.com/assets/189820/15551849/ae1ff85e-226c-11e6-9c10-482d62e4b649.jpg)

![file_000_scaled](https://cloud.githubusercontent.com/assets/189820/15551848/ae1e4554-226c-11e6-9607-71237c801ce7.jpg)

Two of the kinect 1s are still attached to the gray wall (it's actually a velcro wall very handy). The other two kinects were on placed at the left edge of the two portrait displays and slightly in front of the the right side of the three portrait displays.

Unfortunately b/c we have changed setups we can't get you a screen shot.

We have some other issues with the kinect2 setup that we will be posting in a separate issue.
