### ISSUE TITLE
Jetson TK1 doesn't seem to send detections.

### ISSUE THREAD

**Issue by igierard** [OpenPTrack/open_ptrack#99]
We are trying to get PTrack running on the TK1 with a kinect 2 we've followed all the instructions and we've worked around the USB 3.0 issues. Everything seems like it's working. Rviz sees the topics and I can even get a point cloud stream (which seems clean and usable). But we never receive any detections from the device. The only thing that seems suspect. is that we get a lot of

```
[DepthPacketStreamParser::handleNewData] skipping depth packet because processor is not ready
```

We've looked through the trouble shooting docs and can seem to come up with anything. We're using the same detection settings we were using when this camera was running on a PC. Any suggestions?

**Comment by lthursdayl** [comment]
Did you run:

     sudo MaxPerformance &> /dev/null

before starting the detection process? This needs to be rerun each time the TK1 is restarted? You may also need to refer to: https://github.com/OpenPTrack/open_ptrack/wiki/Imager-Settings to ensure your Kinect and tracking processes are sensitive enough.

**Comment by jburkeucla** [comment]
Per my notes this happens in startup in this system
J

-----Original Message-----

**Comment by igierard** [comment]
I did run MaxPerformance and I'm using the same settings that that worked when I was running with a PC (same position and lighting).

**Comment by marketto89** [comment]
@igierard 

It is quite normal to see some
`[DepthPacketStreamParser::handleNewData] skipping depth packet because processor is not ready` 
when you are using the Jetson TK1/TX1. 
In order to check if the Jetson is really in MaxPerformance mode you could post the output of `sudo Status`.
Nevertheless, if you are able to see the point cloud in Rviz then the driver is working correctly. In this case, the issue is to be found in the OpenPTrack configuration you are using.

**Comment by jburkeucla** [comment]
Abandoned issue?
